@startuml
scale max 1024*768

[->DroneMessageHandler : "receive message"

alt sensors data package	
	DroneMessageHandler --> LifeCycle : OnDataMessageReceived
	LifeCycle --> SnapshotProcessor : OnMessageReceived
	SnapshotProcessor --> SnapshotProcessor : "calculate and save message internally"
else end sensor data package
	DroneMessageHandler --> LifeCycle : OnFinalMessageReceived
	LifeCycle --> SnapshotProcessor : GetGeneratedSnapshot

	LifeCycle --> MapAssembler : ProcessNewSnapshot
	MapAssembler --> MapAssembler : "add snapshot to global map"
	LifeCycle --> MapAssembler : GetCurrentMap

	LifeCycle --> MapDetalzationAnalyzer : RecalculateDetalizationPositions
	LifeCycle --> MapDetalzationAnalyzer : GetPositions

	LifeCycle --> DroneMover : GetCurrentPosition
	LifeCycle --> Guide : CalculateWayPoints(cur_pos, det_points)

	LifeCycle --> DroneMover : GenerateMoveSequence(w_p)

	loop move_sequence.size() 
		LifeCycle --> DroneMessageHandler : SendMessageToDroid(m_s)
	end

	LifeCycle --> DroneMessageHandler : SendMessageToDroid(start_scan)
	LifeCycle --> SnapshotProcessor : ClearSnapshot
end

@enduml
